# This is a basic workflow to help you get started with Actions

name: Fastboot Builder

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      URL:
        description: official recovery
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: maximizeYourBuildEnvironment
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: CheckOutWarehouseFiles
        uses: actions/checkout@main
      - name: prepareTheRequiredEnvironment
        run: |
          echo "device=xaga" >> $GITHUB_ENV
          echo "date=$(echo ${{ github.event.inputs.URL }} | cut -d"/" -f4)" >> $GITHUB_ENV
          sudo apt-get install python3 aria2 p7zip-full zstd
      - name: Build ROM
        run: |
          sudo bash "$GITHUB_WORKSPACE"/build.sh ${{ github.event.inputs.URL }} $GITHUB_WORKSPACE
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: fastboot ROM
        run: |
          mkdir -p "$GITHUB_WORKSPACE/GithubRelease"
          cp "$GITHUB_WORKSPACE/${device}_fastboot.zip" "$GITHUB_WORKSPACE/GithubRelease/"
          cd "$GITHUB_WORKSPACE"

      - name: Github Release
        uses: ncipollo/release-action@main
        with:
          artifacts: ${{ github.workspace }}/GithubRelease/*
          name: "${{ env.date }}"
          tag: "${{ env.date }}"
          allowUpdates: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}

