name: Fastboot Builder

on:
  workflow_dispatch:
    inputs:
      URL:
        description: official recovery rom
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: maximizeYourBuildEnvironment
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: CheckOutWarehouseFiles
        uses: actions/checkout@main

      - name: Set Git user info
        run: |
          git config user.email "ajefinojacob9488@gmail.com"
          git config user.name "Jefino9488"
        shell: bash

      - name: prepareTheRequiredEnvironment
        run: |
          # Extract device name from the URL
          URL="${{ github.event.inputs.URL }}"
          device_name=$(basename "$URL" | cut -d'_' -f2 | cut -d'.' -f2)
          echo "device=$device_name" >> $GITHUB_ENV
          echo "Device name: $device_name"

          echo "version=$(echo ${{ github.event.inputs.URL }} | cut -d"/" -f4)" >> $GITHUB_ENV
          sudo apt-get install python3 aria2 p7zip-full zstd

      - name: Build ROM
        run: |
          sudo bash "$GITHUB_WORKSPACE"/build.sh ${{ github.event.inputs.URL }} $GITHUB_WORKSPACE $device_name

      - name: Upload Release
        run: |
          mkdir -p "$GITHUB_WORKSPACE/GithubRelease"
          cd "$GITHUB_WORKSPACE"/GithubRelease
          cp "$GITHUB_WORKSPACE/tools/merge.bat" .
          sudo split -b 1536M -d "$GITHUB_WORKSPACE"/zip/"${{ env.device }}_fastboot.zip" "${{ env.device }}_${{ env.version }}_fastboot-split.zip"
          cd "$GITHUB_WORKSPACE"
          touch file.log
          echo -e "Fastboot version : ${{ env.version }}\n  > file.log

      - name: Create and Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ github.workspace }}/GithubRelease/*
          name: "${{ env.device }}_${{ env.version }}_fastboot"
          tag: "${{ env.device }}_${{ env.version }}"
          artifactErrorsFailBuild: true
          allowUpdates: true
          bodyFile: "${{ github.workspace }}/file.log"
          token: ${{ secrets.GITHUB_TOKEN }}
