name: HyperMod_Fastboot

on:
  workflow_dispatch:
    inputs:
      URL:
        description: official recovery rom
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: maximizeYourBuildEnvironment
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 8192
          root-reserve-mb: 4096
          temp-reserve-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: CheckOutWarehouseFiles
        uses: actions/checkout@main

      - name: Set Git user info
        run: |
          git config user.email "jefinojacob9488@gmail.com"
          git config user.name "Jefino9488"
        shell: bash

      - name: prepareTheRequiredEnvironment
        run: |
          # Extract device name from the URL
          URL="${{ github.event.inputs.URL }}"
          device_name=$(basename "$URL" | cut -d'_' -f2 | cut -d'.' -f2)
          echo "device=$device_name" >> $GITHUB_ENV
          echo "Device name: $device_name"

          echo "version=$(echo ${{ github.event.inputs.URL }} | cut -d"/" -f4)" >> $GITHUB_ENV
          sudo apt-get install python3 aria2 p7zip-full zstd dos2unix

      - name: Build ROM
        run: |
          sudo bash "$GITHUB_WORKSPACE"/Builder/test.sh ${{ github.event.inputs.URL }} ${{ env.device }} $GITHUB_WORKSPACE
          

      - name: Upload ROM
        id: Fastboot-Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.device }}_fastboot
          path: ${{ github.workspace }}/zip/${{ env.device }}_fastboot.zip
          compression-level: 0
          retention-days: 1
